/* Deterministic demo records. No external APIs or persistent customer data. */
window.CompassData=(()=>{
 const products=[{name:'骑士1',price:3299,launch:'2023-01-01',track:'大路灯'},{name:'骑士Z',price:4299,launch:'2023-01-01',track:'大路灯'},{name:'精灵Z',price:1899,launch:'2023-01-01',track:'护眼台灯'},{name:'精灵0',price:1299,launch:'2026-07-08',track:'护眼台灯'},{name:'精灵D',price:2199,launch:null,track:'护眼台灯'}];
 const channels=['天猫','京东POP','京东自营','线下门店'],online=channels.slice(0,3),staff=['Eva','Tim','Cindy','Hogan','Lily','Alex'],audiences=['品牌人群','竞品人群','行业人群','关联人群'],fsNames=['品牌人群','竞品人群','品类人群'];
 const iso=d=>d.toISOString().slice(0,10),date=s=>new Date(s+'T12:00:00Z'),shift=(s,n)=>{let d=date(s);d.setUTCDate(d.getUTCDate()+n);return iso(d)},today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 function monthShift(s,n){const d=date(s),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+n);const end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,end));return iso(d)}
 function hash(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0)/4294967295}
 function split(value,weights){const sum=weights.reduce((a,b)=>a+b,0);if(!sum)return weights.map(()=>0);let a=weights.map(w=>Math.floor(value*w/sum)),left=value-a.reduce((x,y)=>x+y,0);let order=weights.map((w,i)=>({i,f:value*w/sum-a[i]})).sort((a,b)=>b.f-a.f);for(let i=0;i<left;i++)a[order[i%order.length].i]++;return a}
 const ratio=(a,b)=>b?a/b:null;
 const dayCache=new Map();
 function record(day,p,c){const key=day+'|'+p+'|'+c;if(dayCache.has(key))return dayCache.get(key);const product=products[p];if(!product.launch||day<product.launch)return null;const u=hash(key),age=(date(day)-date('2024-01-01'))/86400000;
  const visits=Math.max(0,Math.round([950,720,620,460,250][p]*[1,.58,.75,.07][c]*(1+.13*Math.sin(age/8)+.05*Math.cos(age/3))*(.9+.2*u)*(1+age*.00017)));
  const orders=Math.round(visits*([.024,.029,.036,.04,.019][p]+c*.002)*(.9+.2*u)),sales=orders*product.price,refund=Math.floor(orders*(.035+.03*u));
  const paidOrders=c===3?0:Math.round(orders*(.58+hash(key+'paid')*.12)),paid=paidOrders*product.price,siteSpend=c===3?0:Math.round(sales*[.095,.082,.068][c]*(.92+.16*u)),offlineSpend=c===3?Math.round(sales*.045):0;
  let adVisits=Math.round(visits*(.41+.10*u)),searchVisits=Math.round((visits-adVisits)*(.64+.06*u));let sourceVisits=[adVisits,searchVisits,visits-adVisits-searchVisits];let organic=orders-paidOrders,searchOrders=Math.round(organic*.74),sourceOrders=[paidOrders,searchOrders,organic-searchOrders];
  const sources=sourceVisits.map((v,i)=>({name:['付费推广','搜索','其他免费流量'][i],visits:v,orders:sourceOrders[i],sales:sourceOrders[i]*product.price,cart:Math.round(v*(.095+i*.012+u*.01))}));
  const brandVisits=Math.round(searchVisits*(.36+u*.1)),brandOrders=Math.round(searchOrders*.48);const brand={name:'品牌词',visits:brandVisits,orders:brandOrders,sales:brandOrders*product.price,cart:Math.round(brandVisits*.14)};
  const scenes=c===3?[{name:'门店',visits,orders,sales,refund}]:[['商详',.85,.72],['询单',.09,.26],['直播',.15,.12]].map(([name,v,o])=>{let ord=Math.round(orders*o);return {name,visits:Math.round(visits*v),orders:ord,sales:ord*product.price,refund:0}});
  const inquiry=scenes.find(s=>s.name==='询单');let employees=[];
  if(inquiry){const weights=staff.map((_,i)=>.9+hash(day+p+c+'staff'+i)*.6),vs=split(inquiry.visits,weights),os=split(inquiry.orders,weights.map((v,i)=>v*(.7+hash(day+p+'eff'+i)*.6)));employees=staff.map((name,i)=>({name,visits:vs[i],orders:os[i],sales:os[i]*product.price}))}
  const weights=audiences.map((_,i)=>[.19,.24,.45,.12][i]*(.85+hash(key+'aud'+i)*.3));const asp=split(siteSpend,weights),ap=split(paidOrders,weights.map((v,i)=>v*[1.25,.85,.95,1.15][i])),av=split(adVisits,weights);
  const crowd=audiences.map((name,i)=>({name,spend:asp[i],paid:ap[i]*product.price,clicks:av[i],orders:ap[i],reach:Math.round(av[i]*1.8),pool:Math.round(visits*[14,21,42,18][i])}));
  const xspend=c===3?0:Math.round(sales*(.022+hash(key+'x')*.009)),xc=split(xspend,[.38,.62]);const xorders=Math.round(paidOrders*.24),xcVisits=Math.round(visits*(.035+u*.015)),pgUV=Math.round(visits*(.06+u*.016));const pgSplit=split(xc[0],[.78,.22]);
  const red=[{name:'聚光',spend:xc[0],juguang:pgSplit[0],pinzhuan:pgSplit[1],visits:pgUV,clicks:Math.round(pgUV/(.13+.05*u)),orders:0,sales:0},{name:c===0?'红猫':'红京',spend:xc[1],juguang:0,pinzhuan:0,visits:xcVisits,clicks:xcVisits,orders:xorders,sales:xorders*product.price}];
  const kfs=split(xspend,[.25,.45,.30]),fs=[];
  for(const [type,index]of[['F',1],['S',2]]){const spend=split(kfs[index],[.28,.23,.49]);for(let i=0;i<3;i++){const clicks=Math.round(spend[i]/(type==='F'?1.4+i*.3:7+i)),impressions=Math.round(clicks/(type==='F'?.037:.17)),behavior=Math.round(clicks*(type==='F'?.46:.83)),ti=Math.round(clicks*(.09+u*.03));fs.push({type,name:fsNames[i],spend:spend[i],clicks,impressions,behavior,ti})}}
  const r={day,p,c,visits,orders,sales,paid,paidOrders,siteSpend,offlineSpend,xspend,refund,reason:split(refund,[.76,.24]),cart:sources.reduce((s,x)=>s+x.cart,0),sources,brand,scenes,employees,crowd,red:c===3?[]:red,kfs,fs:c===3?[]:fs};dayCache.set(key,r);return r;
 }
 function rows(start,end,ch=channels,product='all'){let result=[];for(let d=start;d<=end;d=shift(d,1))for(let p=0;p<products.length;p++)if(product==='all'||products[p].name===product)for(let c=0;c<channels.length;c++)if(ch.includes(channels[c])){let r=record(d,p,c);if(r)result.push(r)}return result}
 function sum(rs,fields){const t=Object.fromEntries(fields.map(k=>[k,0]));for(const r of rs)for(const k of fields)t[k]+=r[k]||0;return t}
 function total(rs,scope='global'){const t=sum(rs,['sales','visits','orders','paid','paidOrders','siteSpend','xspend','offlineSpend','refund','cart']);t.onlineSales=rs.filter(r=>r.c<3).reduce((s,r)=>s+r.sales,0);t.spend=t.siteSpend+(scope==='platform'?0:t.xspend);return {...t,conversion:ratio(t.orders,t.visits),aov:ratio(t.sales,t.orders),roi:ratio(t.paid,t.spend),paidShare:ratio(t.paid,t.onlineSales),refundRate:ratio(t.refund,t.orders),cartRate:ratio(t.cart,t.visits)}}
 function source(rs){const aggregate=name=>{let a=rs.flatMap(r=>name==='品牌词'?[r.brand]:r.sources.filter(s=>name==='经营优势（免费）'?s.name!=='付费推广':s.name===name));let t=sum(a,['visits','orders','sales','cart']);return {name,...t,conversion:ratio(t.orders,t.visits),cartRate:ratio(t.cart,t.visits)}};return ['付费推广','经营优势（免费）','搜索','品牌词','其他免费流量'].map(aggregate)}
 function scenes(rs){return ['商详','询单','门店','直播'].map(name=>{const t=sum(rs.flatMap(r=>r.scenes.filter(s=>s.name===name)),['visits','orders','sales']);return {name,...t,conversion:ratio(t.orders,t.visits),aov:ratio(t.sales,t.orders)}})}
 function employees(rs){return staff.map(name=>{const t=sum(rs.flatMap(r=>r.employees.filter(s=>s.name===name)),['visits','orders','sales']);return {name,...t,conversion:ratio(t.orders,t.visits)}}).sort((a,b)=>(b.conversion??-1)-(a.conversion??-1)||a.name.localeCompare(b.name)).map((s,i)=>({...s,rank:s.visits?i+1:null}))}
 function crowd(rs){return audiences.map(name=>{const t=sum(rs.flatMap(r=>r.crowd.filter(s=>s.name===name)),['spend','paid','clicks','orders','reach','pool']);return {name,...t,penetration:ratio(t.reach,t.pool),conversion:ratio(t.orders,t.clicks),roi:ratio(t.paid,t.spend)}})}
 function red(rs){return ['聚光','红猫','红京'].map(name=>{const t=sum(rs.flatMap(r=>r.red.filter(s=>s.name===name)),['spend','juguang','pinzhuan','visits','clicks','orders','sales']);return {name,...t,conversion:ratio(name==='聚光'?t.visits:t.orders,name==='聚光'?t.clicks:t.visits),cost:ratio(t.spend,t.visits),roi:name==='聚光'?null:ratio(t.sales,t.spend)}})}
 function fs(rs,type){const all=rs.flatMap(r=>r.fs.filter(s=>s.type===type)),totalSpend=all.reduce((s,r)=>s+r.spend,0);return [...fsNames,'合计'].map(name=>{const t=sum(name==='合计'?all:all.filter(r=>r.name===name),['spend','clicks','impressions','behavior','ti']);return {name,...t,share:ratio(t.spend,totalSpend),cpc:ratio(t.spend,t.clicks),behaviorRate:ratio(t.behavior,t.clicks),behaviorCost:ratio(t.spend,t.behavior),tiCost:ratio(t.spend,t.ti)}})}
 function budgets(month,end,product='all'){const actual=rows(month+'-01',end,online,product);let result=[];for(let p=0;p<products.length;p++)if(product==='all'||products[p].name===product)for(let i=0;i<3;i++){const launch=products[p].launch,active=launch&&launch<=month+'-31',plan=active?Math.round(([14000,18000,12000,9000,0][p])*(1+hash(month+p+'budget')*.3)*[.25,.45,.30][i]/100)*100:0;result.push({product:products[p].name,channel:['K','F','S'][i],budget:plan,spend:actual.filter(r=>r.p===p).reduce((s,r)=>s+r.kfs[i],0)})}return result}
 function content(month,product='all',cutoff=month+'-31'){let all=[];for(let p=0;p<products.length;p++){if(product!=='all'&&products[p].name!==product)continue;const launch=products[p].launch;if(!launch||launch>month+'-31')continue;let count=34+Math.floor(hash(month+p+'signed')*23);for(let i=0;i<count;i++){let signed=month+'-'+String(1+Math.floor(hash(month+p+'s'+i)*24)).padStart(2,'0'),published=hash(month+p+'pub'+i)>.16?shift(signed,1+Math.floor(hash(month+p+'lag'+i)*4)):null;all.push({p,signed,published,audience:['品牌人群','竞品人群','行业人群'][i%3],type:['选购攻略','产品测评','场景体验','使用指南'][i%4],interactions:Math.floor(hash(month+p+'viral'+i)*1250)})}}
  const scoped=all.filter(r=>r.signed<=cutoff),pub=scoped.filter(r=>r.published&&r.published.startsWith(month)&&r.published<=cutoff);return {records:scoped,published:pub,signed:scoped.length,pubCount:pub.length,viral:pub.filter(r=>r.interactions>=1000).length,rate:ratio(pub.length,scoped.length),viralRate:ratio(pub.filter(r=>r.interactions>=1000).length,pub.length)}}
 function ranking(end,ch,product='all'){const start=end.slice(0,8)+'01',base=total(rows(start,end,[ch],product));return ['柏曼','霍尼','GE','明基'].map((name,i)=>{const f=i===0?1:[1,1.12,.83,.91][i]*(.91+hash(end.slice(0,7)+ch+product+name)*.18),sales=Math.round(base.sales*f),visits=Math.round(base.visits*f*(1+(i*.025)));return {name,sales,visits,conversion:base.conversion===null?null:base.conversion*(i===0?1:.92+hash(end+name)*.12)}}).sort((a,b)=>b.sales-a.sales||a.name.localeCompare(b.name)).map((r,i)=>({...r,rank:base.sales?i+1:null}))}
 function isNew(p,end){const launch=products[p].launch;return !!launch&&launch<=end&&end<monthShift(launch,3)}
 function projects(month,end){const tracks=['大路灯','护眼台灯','氛围照明','配件'];return tracks.map((name,i)=>{const planned=2+Math.floor(hash(month+name+'planned')*4),arrivals=Array.from({length:planned},(_,j)=>1+Math.floor(hash(month+name+j)*28)),actual=arrivals.filter(day=>day<=+end.slice(-2)).length;return {name,newCount:2+Math.floor(hash(month+name+'new')*4),planned,actual,ongoing:6+i}})}
 return {products,channels,online,staff,audiences,fsNames,iso,date,shift,today,monthShift,hash,split,ratio,record,rows,sum,total,source,scenes,employees,crowd,red,fs,budgets,content,ranking,isNew,projects,clear:()=>dayCache.clear()};
})();
