'use strict';
const D=window.CompassData,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const COLORS=['#287965','#9bc690','#7e9ed6','#e3b775','#b7a4ce','#83bbc0'];
let MODE=document.body.dataset.mode==='hero'?'hero':'category',GROUP=MODE==='hero'?'强主推经营':'品类经营';
const pagesFor=MODE=>MODE==='hero'?[['hero','经营总览','▦'],['inside','站内运营管理','▤'],['outside','站外运营管理','◇'],['hero-service','售后','▧']]:[['overview','经营总览','▦'],['race','赛道赛马','◷'],['tmall','天猫','▤'],['jd','京东','▥'],['red','小红书','◇'],['inquiry','询单','◉'],['service','售后','▧']];let PAGES=pagesFor(MODE);
const DESCS={overview:'全域结果、渠道贡献与转化承接。',hero:'单品贡献、品类基准与投放回报。',race:'项目推进、产品来源与新品成长。',tmall:'天猫站内流量、付费成交与人群表现。',jd:'京东合计与 POP、自营分店经营表现。',red:'聚光进店、红猫与红京归因、月度预算。',inquiry:'同一份询单明细，贯通平台、客服与商品。',inside:'单品站内流量、竞争对比与人群推广。',outside:'站外投放、预算、人群与内容运营。',service:'原表待定收录，暂未定义数值指标。','hero-service':'原表保留两类退货，统计口径待确认。'};
let latest=D.shift(D.today(),-1);
let state={page:PAGES[0][0],product:MODE==='hero'?'骑士1':'all',shop:'all',start:latest.slice(0,8)+'01',end:latest,period:'month',metric:'sales'};
const nf=new Intl.NumberFormat('zh-CN',{maximumFractionDigits:0}),n=v=>v===null||v===undefined?'—':nf.format(v),pct=v=>v===null||v===undefined?'—':(v*100).toFixed(2)+'%',money=v=>v===null||v===undefined?'—':'¥'+n(v),decimal=v=>v===null||v===undefined?'—':v.toFixed(2),cost=v=>v===null||v===undefined?'—':'¥'+v.toFixed(2),compact=v=>v===null||v===undefined?'—':Math.abs(v)>=10000?(v/10000).toFixed(2)+'万':n(v);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const RATE=new Set(['conversion','refundRate','paidShare','salesShare','adShare','penetration','cartRate','share','behaviorRate','rate','viralRate']);
const CASH=new Set(['sales','spend','paid','budget','siteSpend','xspend','offlineSpend','juguang','pinzhuan']);
function format(k,v){return RATE.has(k)?pct(v):CASH.has(k)?money(v):['aov','cpc','cost','behaviorCost','tiCost'].includes(k)?cost(v):k==='roi'?decimal(v):n(v)}
function compare(v,b,k,label){if(v===null||v===undefined||b===null||b===undefined)return `<span class="compare muted">${label} 暂无可比数据</span>`;let diff=RATE.has(k)?(v-b)*100:b===0?null:(v/b-1)*100;if(diff===null)return `<span class="compare muted">${label} 基期为0</span>`;const inverse=['refundRate','cpc','cost','behaviorCost','tiCost'].includes(k),positive=inverse?diff<=0:diff>=0;return `<span class="compare ${positive?'positive':'negative'}" title="${label}基期：${format(k,b)}">${label} ${diff>0?'+':''}${diff.toFixed(2)}${RATE.has(k)?'pp':'%'}</span>`}
function valueCell(v,k,y,p){const label=y!==null&&y!==undefined?'同比':'环比',base=label==='同比'?y:p;return `<span class="cell-value" data-order="${v??''}">${format(k,v)}</span>${compare(v,base,k,label)}`}
function card(label,k,t,y,p,primary=false){let v=t[k];return `<article class="stat ${primary?'primary':''}"><div class="stat-top">${label}<span class="stat-symbol">${primary?'↗':'◌'}</span></div><div class="stat-number">${CASH.has(k)?compact(v):RATE.has(k)?pct(v):k==='aov'?n(v):k==='roi'?decimal(v):compact(v)}<small>${CASH.has(k)||k==='aov'?'元':k==='visits'?'人次':k==='roi'?'倍':''}</small></div><div class="stat-foot">${compare(v,y?.[k],k,'同比')}${compare(v,p?.[k],k,'环比')}</div></article>`}
function simpleCard(label,value,note,primary=false){return `<article class="stat ${primary?'primary':''}"><div class="stat-top">${label}</div><div class="stat-number">${value}</div><div class="stat-foot">${note}</div></article>`}
function note(text,type=''){return `<div class="insight ${type}">${text}</div>`}
function scope(){if(state.page==='tmall')return ['天猫'];if(state.page==='jd')return state.shop==='all'?['京东POP','京东自营']:[state.shop];if(['inside','inquiry'].includes(state.page))return state.shop==='all'?D.online:[state.shop];if(['red','outside','race'].includes(state.page))return D.channels;return state.shop==='all'?D.channels:[state.shop]}
function context(product=state.product,channels=scope(),scopeType=['tmall','jd','inside'].includes(state.page)?'platform':'global'){
 const days=Math.round((D.date(state.end)-D.date(state.start))/86400000)+1,prevStart=D.shift(state.start,-days),prevEnd=D.shift(state.start,-1),yearStart=D.monthShift(state.start,-12),yearEnd=D.monthShift(state.end,-12);
 const rs=D.rows(state.start,state.end,channels,product),yrs=D.rows(yearStart,yearEnd,channels,product),prs=D.rows(prevStart,prevEnd,channels,product);
 return {rs,yrs,prs,t:D.total(rs,scopeType),yt:yrs.length?D.total(yrs,scopeType):null,pt:prs.length?D.total(prs,scopeType):null,days,channels,product,scopeType,prevStart,prevEnd,yearStart,yearEnd};
}
function sliceContext(c,channels,product=c.product){const filter=rs=>rs.filter(r=>channels.includes(D.channels[r.c])&&(product==='all'||D.products[r.p].name===product));const rs=filter(c.rs),yrs=filter(c.yrs),prs=filter(c.prs);return {...c,rs,yrs,prs,channels,product,t:D.total(rs,c.scopeType),yt:yrs.length?D.total(yrs,c.scopeType):null,pt:prs.length?D.total(prs,c.scopeType):null}}
function columnCells(row,columns,y,p){return columns.map(k=>valueCell(row[k],k,y?.[k],p?.[k]))}
const compareNote='主值下方显示同比；无同期记录则显示环比。百分率变化为百分点（pp）。';
function trend(c,metric=state.metric,title='经营趋势'){let labels=[],a=[],b=[];for(let d=state.start;d<=state.end;d=D.shift(d,1)){labels.push(d.slice(5));a.push(D.total(c.rs.filter(r=>r.day===d),c.scopeType)[metric]??0);b.push(D.total(c.prs.filter(r=>r.day===D.shift(d,-c.days)),c.scopeType)[metric]??0)}let opts={sales:'销售额',visits:'访问人次',roi:'付费ROI'};return panel(title,'上期：'+c.prevStart+' — '+c.prevEnd,line(labels,[{name:'本期',values:a},{name:'上期',values:b}],metric==='roi'?decimal:compact),`<div class="chart-tabs">${Object.entries(opts).map(([k,v])=>`<button data-metric="${k}" class="${metric===k?'active':''}">${v}</button>`).join('')}</div>`)}
function breakdownGroups(channels){const a=[];if(channels.includes('天猫'))a.push({name:'天猫',ch:['天猫']});let jd=channels.filter(ch=>ch.startsWith('京东'));if(jd.length>1)a.push({name:'京东合计',ch:jd});for(let ch of jd)a.push({name:jd.length>1?'↳ '+ch:ch,ch:[ch]});if(channels.includes('线下门店'))a.push({name:'线下门店',ch:['线下门店']});return a}
function channelValues(start,end,ch,product,hero){const t=D.total(D.rows(start,end,ch,product),'platform'),category=D.total(D.rows(start,end,hero?ch:D.channels,'all')),global=D.total(D.rows(start,end,D.channels,'all'));
 return {...t,salesShare:D.ratio(t.sales,category.sales),adShare:D.ratio(t.siteSpend,hero?category.siteSpend:global.spend)};}
function channelPanel(c){const hero=MODE==='hero',cols=['sales','salesShare','visits','conversion','aov','spend','adShare','roi','refundRate'];let data=breakdownGroups(c.channels).map(({name,ch})=>{const r=channelValues(state.start,state.end,ch,c.product,hero),hasY=D.rows(c.yearStart,c.yearEnd,ch,c.product).length,hasP=D.rows(c.prevStart,c.prevEnd,ch,c.product).length,y=hasY?channelValues(c.yearStart,c.yearEnd,ch,c.product,hero):null,p=hasP?channelValues(c.prevStart,c.prevEnd,ch,c.product,hero):null;return [name,...columnCells(r,cols,y,p)]});
 return panel('渠道经营表现',compareNote,table(['渠道','销售额',hero?'单品占品类销售':'渠道品类销售占比','访客人次','转化率','客单价','站内广告消耗',hero?'单品广告费占比':'平台广告费占比','站内付费ROI','退款率'],data)+`<p class="note">京东合计包含下方POP与自营，不重复累加。${hero?'单品销售、广告占比分母分别为同平台全品类销售和站内消耗。':'销售占比分母为全品类全渠道销售；平台广告费占比分母为全品类全域广告消耗。'}占比分母为演示口径，待业务确认。</p>`)}
function scenePanel(c){const get=(rs,start,end)=>D.scenes(rs).map(r=>({...r,salesShare:D.ratio(r.sales,D.total(D.rows(start,end,D.channels,'all')).sales)}));const a=get(c.rs,state.start,state.end),y=c.yrs.length?get(c.yrs,c.yearStart,c.yearEnd):[],p=c.prs.length?get(c.prs,c.prevStart,c.prevEnd):[];return panel('转化场景',compareNote,table(['场景','归因销售额','品类销售占比','场景流量','转化率','客单价'],a.map((r,i)=>[r.name,...columnCells(r,['sales','salesShare','visits','conversion','aov'],y[i],p[i])]))+`<p class="note">商详、询单、直播仅含线上；门店按到店人次。场景可以重叠，归因成交不与平台成交相加。占比分母固定为全品类全渠道销售（演示口径待确认）。</p>`)}
function rankPanel(){return panel('行业排名','截至 '+state.end+' · 当月累计销售额排名 · 同一范围共用榜单',table(['平台','柏曼','霍尼','GE','明基'],D.online.map(ch=>{const list=D.ranking(state.end,ch,state.product);return [ch,...['柏曼','霍尼','GE','明基'].map(name=>{let rank=list.find(r=>r.name===name).rank;return rank?`<span class="rank">第 ${rank} 名</span>`:'暂无排名'})]}))+`<p class="note">全部为模拟竞品数据，不代表真实市场排名。</p>`)}
function redPanel(c){const a=D.red(c.rs),y=c.yrs.length?D.red(c.yrs):[],p=c.prs.length?D.red(c.prs):[];const cells=a.map((r,i)=>[r.name,r.name==='聚光'?'—':valueCell(r.sales,'sales',y[i]?.sales,p[i]?.sales),...columnCells(r,['visits','conversion','spend','cost'],y[i],p[i]),r.name==='聚光'?'—':valueCell(r.roi,'roi',y[i]?.roi,p[i]?.roi)]);return panel('小红书运营情况',compareNote,table(['渠道','归因销售额','进店UV','转化率','广告消耗','进店UV成本','普通归因ROI'],cells)+`<p class="note">聚光消耗（${money(a[0].spend)}）= 聚光 ${money(a[0].juguang)} + 品专 ${money(a[0].pinzhuan)}。聚光转化=进店UV/点击；红猫与红京转化=归因订单/进店UV。红猫、红京成交已包含在线上付费成交内，不重复加总。</p>`+note('原表“护眼灯按直接成交/2”含义待确认，当前展示普通ROI，未启用该特殊规则。'))}
function overview(c){const hero=MODE==='hero';let cards=[['销售额','sales'],['访问人次','visits'],['支付转化率','conversion'],['客单价','aov'],['总广告消耗','spend'],[hero?'站内付费成交金额':'站内付费成交占比',hero?'paid':'paidShare'],['总付费ROI','roi'],[hero?'站内付费成交占比':'站内付费成交金额',hero?'paidShare':'paid']];return `<div class="stats">${cards.map(([name,k],i)=>card(name,k,c.t,c.yt,c.pt,i===0)).join('')}</div>${note('演示口径：总广告=站内+小红书，不含线下费用（待确认）；付费成交仅含天猫、京东。全域ROI采用站内去重付费成交/总广告消耗。')}<div class="grid">${trend(c)}${panel('渠道销售构成','按支付金额 · 不包含重复归因',donut(c.channels,c.channels.map(ch=>D.total(c.rs.filter(r=>D.channels[r.c]===ch)).sales)))}</div>${channelPanel(c)}<div class="grid equal">${rankPanel()}${panel('平台销售对比','各独立渠道 · 元',bars(c.channels,[{name:'销售额',values:c.channels.map(ch=>D.total(c.rs.filter(r=>D.channels[r.c]===ch)).sales)}]))}</div>${scenePanel(c)}${redPanel(c)}`}
const views={overview,hero:overview};
function render(){$$('[data-mode-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.modeTab===MODE);b.setAttribute('aria-pressed',String(b.dataset.modeTab===MODE))});$('.workspace-label').innerHTML=GROUP+'罗盘 <span>DEMO</span>';document.body.dataset.mode=MODE;const page=PAGES.find(p=>p[0]===state.page)||PAGES[0];$('#title').textContent=page[1];$('#breadcrumb').textContent=GROUP;$('#eyebrow').textContent=MODE==='hero'?'HERO PRODUCT PERFORMANCE':'CATEGORY PERFORMANCE';$('#subtitle').textContent=DESCS[state.page];document.title=`${GROUP} · ${page[1]} · 柏曼`;$('#nav').innerHTML=`<div class="nav-group">${GROUP}</div>`+PAGES.map(p=>`<button class="nav-item ${state.page===p[0]?'active':''}" data-page="${p[0]}" ${state.page===p[0]?'aria-current="page"':''}><span class="nav-icon">${p[2]}</span>${p[1]}${p[0].includes('service')?'<small>待定</small>':''}</button>`).join('');
 $('#product').innerHTML=(MODE==='category'?'<option value="all">全部产品</option>':'')+D.products.map(p=>`<option value="${p.name}">${p.name}${p.launch?'':' · 待上架'}</option>`).join('');$('#product').value=state.product;
 const shops=state.page==='jd'?['京东POP','京东自营']:['inside','inquiry'].includes(state.page)?D.online:D.channels;$('#shop').innerHTML='<option value="all">全部店铺</option>'+shops.map(ch=>`<option>${ch}</option>`).join('');if(!shops.includes(state.shop)&&state.shop!=='all')state.shop='all';$('#shop').value=state.shop;$('#shop-wrap').style.display=['race','red','outside','service','hero-service','tmall'].includes(state.page)?'none':'flex';
 for(let k of ['start','end']){$('#'+k).value=state[k];$('#'+k).max=latest;$('#'+k).min='2025-01-01'}$$('[data-days]').forEach(b=>b.classList.toggle('active',b.dataset.days===String(state.period)));$('#range-label').textContent=`${state.start} — ${state.end} · ${state.product==='all'?'全品类':state.product}`;$('#updated').textContent=`北京时间 · 模拟数据截至 ${latest}`;
 const c=context(),pending=state.product!=='all'&&!D.products.find(p=>p.name===state.product).launch;$('#content').innerHTML=(pending?note('精灵D · 待上架。保留原表状态；销售、投放与内容均无记录，比例显示“—”。'):'')+(views[state.page]?views[state.page](c):'');$('#content').dataset.page=state.page;
}
function navigate(page){if(!PAGES.some(p=>p[0]===page))return;state.page=page;state.shop='all';state.metric='sales';location.hash=MODE+'/'+page;render();$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'instant'})}
let toastTimer;function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function validDates(a,b){return /^\d{4}-\d{2}-\d{2}$/.test(a)&&/^\d{4}-\d{2}-\d{2}$/.test(b)&&Number.isFinite(+D.date(a))&&Number.isFinite(+D.date(b))&&D.iso(D.date(a))===a&&D.iso(D.date(b))===b&&a>= '2025-01-01'&&a<=b&&b<=latest&&(D.date(b)-D.date(a))/86400000<=365}
function bind(){document.addEventListener('click',e=>{const tab=e.target.closest('[data-mode-tab]');if(tab)switchMode(tab.dataset.modeTab);const p=e.target.closest('[data-page]');if(p)navigate(p.dataset.page);const m=e.target.closest('[data-metric]');if(m){state.metric=m.dataset.metric;render()}const b=e.target.closest('[data-days]');if(b){state.period=b.dataset.days;state.end=latest;state.start=b.dataset.days==='month'?latest.slice(0,8)+'01':D.shift(latest,1-Number(b.dataset.days));render()}const sort=e.target.closest('[data-sort]');if(sort){const t=sort.closest('table'),i=+sort.dataset.sort,desc=sort.dataset.dir!=='desc';sort.dataset.dir=desc?'desc':'asc';const read=cell=>cell.querySelector('[data-order]')?.dataset.order??cell.textContent;[...t.tBodies[0].rows].sort((a,b)=>{let av=read(a.cells[i]),bv=read(b.cells[i]),an=Number(av.replace(/[^\d.-]/g,'')),bn=Number(bv.replace(/[^\d.-]/g,''));return (/\d/.test(av)&&/\d/.test(bv)?an-bn:av.localeCompare(bv,'zh-CN'))*(desc?-1:1)}).forEach(r=>t.tBodies[0].append(r))}});
 $('#product').addEventListener('change',e=>{state.product=e.target.value;render()});$('#shop').addEventListener('change',e=>{state.shop=e.target.value;render()});for(const id of ['start','end'])$('#'+id).addEventListener('change',()=>{const a=$('#start').value,b=$('#end').value;if(!validDates(a,b)){toast('请选择有效日期，范围不超过366天且截至昨日');render();return}state.start=a;state.end=b;state.period='custom';render()});$('#refresh').addEventListener('click',()=>{updateDate();D.clear();render();toast('模拟数据已重新读取，历史记录保持一致')});$('#menu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#data-info').addEventListener('click',()=>$('#info-dialog').showModal());$('#close-info').addEventListener('click',()=>$('#info-dialog').close());$('#info-dialog').addEventListener('click',e=>{if(e.target===$('#info-dialog'))$('#info-dialog').close()});window.addEventListener('hashchange',readRoute);window.matchMedia('(max-width:700px)').addEventListener('change',render);
 const tooltip=document.createElement('div');tooltip.className='chart-tooltip';document.body.append(tooltip);document.addEventListener('pointermove',e=>{const target=e.target.closest('[data-tip]');if(!target){tooltip.style.display='none';return}tooltip.textContent=target.dataset.tip;tooltip.style.display='block';tooltip.style.left=Math.min(e.clientX+12,innerWidth-tooltip.offsetWidth-12)+'px';tooltip.style.top=Math.max(8,e.clientY-tooltip.offsetHeight-12)+'px'});document.addEventListener('scroll',()=>tooltip.style.display='none',true);setInterval(()=>{if(updateDate())render()},60000);
}
function updateDate(){const next=D.shift(D.today(),-1);if(next===latest)return false;latest=next;D.clear();if(state.period!=='custom'){state.end=latest;state.start=state.period==='month'?latest.slice(0,8)+'01':D.shift(latest,1-Number(state.period))}return true}
const savedStates={};
function switchMode(mode,page){if(!['category','hero'].includes(mode))return;if(mode!==MODE){savedStates[MODE]={...state};MODE=mode;GROUP=mode==='hero'?'强主推经营':'品类经营';PAGES=pagesFor(mode);state=savedStates[mode]||{page:PAGES[0][0],product:mode==='hero'?'骑士1':'all',shop:'all',start:latest.slice(0,8)+'01',end:latest,period:'month',metric:'sales'};if(state.period!=='custom'){state.end=latest;state.start=state.period==='month'?latest.slice(0,8)+'01':D.shift(latest,1-Number(state.period))}}if(page&&PAGES.some(p=>p[0]===page)){state.page=page;state.shop='all';state.metric='sales'}location.hash=MODE+'/'+state.page;render();$('#sidebar').classList.remove('open')}
function readRoute(){let [mode,page]=location.hash.slice(1).split('/');if(!['category','hero'].includes(mode)){page=mode;mode=pagesFor('hero').some(p=>p[0]===page)?'hero':'category'}if(mode!==MODE||page!==state.page)switchMode(mode,page)}
window.addEventListener('DOMContentLoaded',()=>{bind();readRoute();render();if(location.protocol==='file:')$('#logout').hidden=true});
